package ponyagons.hiita.repository.entities;

public class CategoryFortuneWithBLOBs extends CategoryFortune {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category_fortune.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category_fortune.opinion
     *
     * @mbg.generated
     */
    private String opinion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category_fortune.content
     *
     * @return the value of category_fortune.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category_fortune.content
     *
     * @param content the value for category_fortune.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category_fortune.opinion
     *
     * @return the value of category_fortune.opinion
     *
     * @mbg.generated
     */
    public String getOpinion() {
        return opinion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category_fortune.opinion
     *
     * @param opinion the value for category_fortune.opinion
     *
     * @mbg.generated
     */
    public void setOpinion(String opinion) {
        this.opinion = opinion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_fortune
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CategoryFortuneWithBLOBs other = (CategoryFortuneWithBLOBs) that;
        return (this.getOmikujiId() == null ? other.getOmikujiId() == null : this.getOmikujiId().equals(other.getOmikujiId()))
            && (this.getCategory() == null ? other.getCategory() == null : this.getCategory().equals(other.getCategory()))
            && (this.getScore() == null ? other.getScore() == null : this.getScore().equals(other.getScore()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()))
            && (this.getOpinion() == null ? other.getOpinion() == null : this.getOpinion().equals(other.getOpinion()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_fortune
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getOmikujiId() == null) ? 0 : getOmikujiId().hashCode());
        result = prime * result + ((getCategory() == null) ? 0 : getCategory().hashCode());
        result = prime * result + ((getScore() == null) ? 0 : getScore().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        result = prime * result + ((getOpinion() == null) ? 0 : getOpinion().hashCode());
        return result;
    }
}