package ponyagons.hiita.repository.entities;

public class CategoryFortuneKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category_fortune.omikuji_id
     *
     * @mbg.generated
     */
    private Integer omikujiId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category_fortune.category
     *
     * @mbg.generated
     */
    private Integer category;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category_fortune.omikuji_id
     *
     * @return the value of category_fortune.omikuji_id
     *
     * @mbg.generated
     */
    public Integer getOmikujiId() {
        return omikujiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category_fortune.omikuji_id
     *
     * @param omikujiId the value for category_fortune.omikuji_id
     *
     * @mbg.generated
     */
    public void setOmikujiId(Integer omikujiId) {
        this.omikujiId = omikujiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category_fortune.category
     *
     * @return the value of category_fortune.category
     *
     * @mbg.generated
     */
    public Integer getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category_fortune.category
     *
     * @param category the value for category_fortune.category
     *
     * @mbg.generated
     */
    public void setCategory(Integer category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_fortune
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CategoryFortuneKey other = (CategoryFortuneKey) that;
        return (this.getOmikujiId() == null ? other.getOmikujiId() == null : this.getOmikujiId().equals(other.getOmikujiId()))
            && (this.getCategory() == null ? other.getCategory() == null : this.getCategory().equals(other.getCategory()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_fortune
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getOmikujiId() == null) ? 0 : getOmikujiId().hashCode());
        result = prime * result + ((getCategory() == null) ? 0 : getCategory().hashCode());
        return result;
    }
}