package ponyagons.hiita.repository.entities;

public class CategoryFortune extends CategoryFortuneKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category_fortune.score
     *
     * @mbg.generated
     */
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category_fortune.score
     *
     * @return the value of category_fortune.score
     *
     * @mbg.generated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category_fortune.score
     *
     * @param score the value for category_fortune.score
     *
     * @mbg.generated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_fortune
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CategoryFortune other = (CategoryFortune) that;
        return (this.getOmikujiId() == null ? other.getOmikujiId() == null : this.getOmikujiId().equals(other.getOmikujiId()))
            && (this.getCategory() == null ? other.getCategory() == null : this.getCategory().equals(other.getCategory()))
            && (this.getScore() == null ? other.getScore() == null : this.getScore().equals(other.getScore()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_fortune
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getOmikujiId() == null) ? 0 : getOmikujiId().hashCode());
        result = prime * result + ((getCategory() == null) ? 0 : getCategory().hashCode());
        result = prime * result + ((getScore() == null) ? 0 : getScore().hashCode());
        return result;
    }
}