package ponyagons.hiita.repository.entities;

public class Omikuji {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column omikuji.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column omikuji.owner
     *
     * @mbg.generated
     */
    private Integer owner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column omikuji.shrine_id
     *
     * @mbg.generated
     */
    private Integer shrineId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column omikuji.fortune
     *
     * @mbg.generated
     */
    private String fortune;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column omikuji.id
     *
     * @return the value of omikuji.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column omikuji.id
     *
     * @param id the value for omikuji.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column omikuji.owner
     *
     * @return the value of omikuji.owner
     *
     * @mbg.generated
     */
    public Integer getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column omikuji.owner
     *
     * @param owner the value for omikuji.owner
     *
     * @mbg.generated
     */
    public void setOwner(Integer owner) {
        this.owner = owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column omikuji.shrine_id
     *
     * @return the value of omikuji.shrine_id
     *
     * @mbg.generated
     */
    public Integer getShrineId() {
        return shrineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column omikuji.shrine_id
     *
     * @param shrineId the value for omikuji.shrine_id
     *
     * @mbg.generated
     */
    public void setShrineId(Integer shrineId) {
        this.shrineId = shrineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column omikuji.fortune
     *
     * @return the value of omikuji.fortune
     *
     * @mbg.generated
     */
    public String getFortune() {
        return fortune;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column omikuji.fortune
     *
     * @param fortune the value for omikuji.fortune
     *
     * @mbg.generated
     */
    public void setFortune(String fortune) {
        this.fortune = fortune;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table omikuji
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Omikuji other = (Omikuji) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getOwner() == null ? other.getOwner() == null : this.getOwner().equals(other.getOwner()))
            && (this.getShrineId() == null ? other.getShrineId() == null : this.getShrineId().equals(other.getShrineId()))
            && (this.getFortune() == null ? other.getFortune() == null : this.getFortune().equals(other.getFortune()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table omikuji
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOwner() == null) ? 0 : getOwner().hashCode());
        result = prime * result + ((getShrineId() == null) ? 0 : getShrineId().hashCode());
        result = prime * result + ((getFortune() == null) ? 0 : getFortune().hashCode());
        return result;
    }
}