package ponyagons.hiita.repository.entities;

public class Shrine {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shrine.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shrine.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shrine.specialty
     *
     * @mbg.generated
     */
    private Integer specialty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shrine.img
     *
     * @mbg.generated
     */
    private String img;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shrine.id
     *
     * @return the value of shrine.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shrine.id
     *
     * @param id the value for shrine.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shrine.name
     *
     * @return the value of shrine.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shrine.name
     *
     * @param name the value for shrine.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shrine.specialty
     *
     * @return the value of shrine.specialty
     *
     * @mbg.generated
     */
    public Integer getSpecialty() {
        return specialty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shrine.specialty
     *
     * @param specialty the value for shrine.specialty
     *
     * @mbg.generated
     */
    public void setSpecialty(Integer specialty) {
        this.specialty = specialty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shrine.img
     *
     * @return the value of shrine.img
     *
     * @mbg.generated
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shrine.img
     *
     * @param img the value for shrine.img
     *
     * @mbg.generated
     */
    public void setImg(String img) {
        this.img = img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shrine
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Shrine other = (Shrine) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getSpecialty() == null ? other.getSpecialty() == null : this.getSpecialty().equals(other.getSpecialty()))
            && (this.getImg() == null ? other.getImg() == null : this.getImg().equals(other.getImg()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shrine
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getSpecialty() == null) ? 0 : getSpecialty().hashCode());
        result = prime * result + ((getImg() == null) ? 0 : getImg().hashCode());
        return result;
    }
}