package ponyagons.hiita.repository.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import ponyagons.hiita.repository.entities.CategoryFortune;
import ponyagons.hiita.repository.entities.CategoryFortuneExample;
import ponyagons.hiita.repository.entities.CategoryFortuneKey;
import ponyagons.hiita.repository.entities.CategoryFortuneWithBLOBs;

@Mapper
public interface CategoryFortuneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_fortune
     *
     * @mbg.generated
     */
    long countByExample(CategoryFortuneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_fortune
     *
     * @mbg.generated
     */
    int deleteByExample(CategoryFortuneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_fortune
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(CategoryFortuneKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_fortune
     *
     * @mbg.generated
     */
    int insert(CategoryFortuneWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_fortune
     *
     * @mbg.generated
     */
    int insertSelective(CategoryFortuneWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_fortune
     *
     * @mbg.generated
     */
    List<CategoryFortuneWithBLOBs> selectByExampleWithBLOBs(CategoryFortuneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_fortune
     *
     * @mbg.generated
     */
    List<CategoryFortune> selectByExample(CategoryFortuneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_fortune
     *
     * @mbg.generated
     */
    CategoryFortuneWithBLOBs selectByPrimaryKey(CategoryFortuneKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_fortune
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") CategoryFortuneWithBLOBs row, @Param("example") CategoryFortuneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_fortune
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") CategoryFortuneWithBLOBs row, @Param("example") CategoryFortuneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_fortune
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") CategoryFortune row, @Param("example") CategoryFortuneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_fortune
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CategoryFortuneWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_fortune
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(CategoryFortuneWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_fortune
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CategoryFortune row);
}