package ponyagons.hiita.repository.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import ponyagons.hiita.repository.entities.Omikuji;
import ponyagons.hiita.repository.entities.OmikujiExample;

@Mapper
public interface OmikujiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table omikuji
     *
     * @mbg.generated
     */
    long countByExample(OmikujiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table omikuji
     *
     * @mbg.generated
     */
    int deleteByExample(OmikujiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table omikuji
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table omikuji
     *
     * @mbg.generated
     */
    int insert(Omikuji row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table omikuji
     *
     * @mbg.generated
     */
    int insertSelective(Omikuji row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table omikuji
     *
     * @mbg.generated
     */
    List<Omikuji> selectByExample(OmikujiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table omikuji
     *
     * @mbg.generated
     */
    Omikuji selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table omikuji
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") Omikuji row, @Param("example") OmikujiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table omikuji
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") Omikuji row, @Param("example") OmikujiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table omikuji
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Omikuji row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table omikuji
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Omikuji row);
}