package ponyagons.hiita.repository.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import ponyagons.hiita.repository.entities.Shrine;
import ponyagons.hiita.repository.entities.ShrineExample;

@Mapper
public interface ShrineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shrine
     *
     * @mbg.generated
     */
    long countByExample(ShrineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shrine
     *
     * @mbg.generated
     */
    int deleteByExample(ShrineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shrine
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shrine
     *
     * @mbg.generated
     */
    int insert(Shrine row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shrine
     *
     * @mbg.generated
     */
    int insertSelective(Shrine row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shrine
     *
     * @mbg.generated
     */
    List<Shrine> selectByExampleWithBLOBs(ShrineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shrine
     *
     * @mbg.generated
     */
    List<Shrine> selectByExample(ShrineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shrine
     *
     * @mbg.generated
     */
    Shrine selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shrine
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") Shrine row, @Param("example") ShrineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shrine
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") Shrine row, @Param("example") ShrineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shrine
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") Shrine row, @Param("example") ShrineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shrine
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Shrine row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shrine
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Shrine row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shrine
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Shrine row);
}